### ISSUE TITLE
javascript warnings about deprecation

### ISSUE THREAD

**Issue by arteck** [sja/ioBroker.pilight#1]
javascript.1	2017-01-07 08:38:34.521	warn	Wrong type of pilight.0.rKuche.state: "boolean". Please fix, while deprecated and will not work in next versions.

**Comment by sja** [comment]
Note to myself: https://github.com/ioBroker/ioBroker.javascript/issues/10

**Comment by arteck** [comment]
ja aber.... :-)

das Problem ist auch wenn ich in Blockly den Zustand wahr oder unwahr nehme..

**Comment by sja** [comment]
Mit "note to myself" gebe ich mir einen Hinweis, wo der Fehler liegt. Das hat nix mit Blockly oder so zu tun.
